name: TiKV-Class-DSS

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/project-dss/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Build and Test project dss
        working-directory: ./project-dss
        run: |
          make test_others
